kind: KafkaUser
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
  namespace: client-kafka-cluster
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          key: my-password
          name: my-kafka-password
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
        host: '*'
      - resource:
          type: group
          name: my-group
          patternType: literal
        operations:
          - Read
        host: '*'
      - host: '*'
        operations:
          - All
        resource:
          type: cluster

